### ISSUE TITLE
"This webpage is not available  ERR_INVALID_CHUNKED_ENCODING"

### ISSUE THREAD

**Issue by venkat7be1** [krys-g/TrotiNet#15]
Accessing few websites leave a message as 
"This webpage is not available  ERR_INVALID_CHUNKED_ENCODING"
EX: http://www.tupaki.com/index.php

How can this issue can be fixed?

**Comment by krys-g** [comment]
Do you mean the error message is displayed in the browser window itself? I failed to reproduce the problem on my side. Can you isolate a particular resource that is affected? (e.g. a URL to an image or html page)

**Comment by krys-g** [comment]
Closed due to lack of activity.
