### ISSUE TITLE
Elements that are tagged to 

### ISSUE THREAD

**Issue by venkat7be1** [krys-g/TrotiNet#16]
Images that are tied to data-src are not displaying in the browser, Here is the example

http://www.nytimes.com/interactive/2015/05/13/us/investigating-the-philadelphia-amtrak-train-crash.html?hp&action=click&pgtype=Homepage&module=a-lede-package-region&region=top-news&WT.nav=top-news&_r=0

Any idea how this can be resolved?

**Comment by krys-g** [comment]
Again, I fail to reproduce the problem on my side... Are you using the example proxy in Example/ ? If so, do you see anything suspicious in the console logs?

**Comment by krys-g** [comment]
Closed due to lack of activity.
